services:
  swapify_db:
    image: postgres:16.1
    restart: always
    env_file: .env.docker
    ports:
      - 5432:5432
    volumes:
      - swapify_db_data:/var/lib/postgresql/data

  swapify_db_test:
    image: postgres:16.1
    restart: always
    env_file: .env.test.docker
    ports:
      - 54321:5432

volumes:
  swapify_db_data:

