providers = ["node"]

[variables]
# CADDY_VERSION = '2.8.2'
NIXPACKS_NODE_VERSION = '20'

[phases.setup]
nixPkgs = ['...', 'jq']
nixpkgsArchive = '505ad1607f7e54426cfb2d804e48fa2c247f32ba'

[phases.codegen]
dependsOn = ['install']
cmds = [
        'pnpm run prepare'
]

[phases.build]
dependsOn = ["...", "codegen"]
cmds = [
        "export VITE_APP_VERSION=$(cat package.json | jq -r '.version')",
        "pnpm run build"
]


[phases.sourcemaps]
dependsOn = ['build']
cmds = [
        "export VITE_APP_VERSION=$(cat package.json | jq -r '.version')",
        'npx --yes @highlight-run/sourcemap-uploader upload --apiKey ${HIGHLIGHT_API_KEY} --path ./dist --appVersion ${VITE_APP_VERSION}',
        "find dist -name '*.js.map' -type f -delete"
]

[start]
cmd = "node dist/server/entry.mjs"
